apiVersion: batch/v1
kind: CronJob
metadata:
  name: NAME-build-cron
  labels:
    app.kubernetes.part-of: NAME-website 
spec:
  schedule: "0/7 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: domaindrivenarchitecture/c4k-website-build
            name: NAME-build-app
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: BUILD_CPU_REQUEST
                memory: BUILD_MEMORY_REQUEST
              limits:
                cpu: BUILD_CPU_LIMIT
                memory: BUILD_MEMORY_LIMIT
            command: ["/entrypoint.sh"]
            envFrom:
            - secretRef:
                name: NAME-secret
            env:
            - name: SHA256SUM
              value: CHECK_SUM
            - name: SCRIPTFILE
              value: SCRIPT_FILE
            volumeMounts:
            - name: content-volume
              mountPath: /var/www/html/website
            - name: hashfile-volume
              mountPath: /var/hashfile.d
          volumes:
          - name: content-volume
            persistentVolumeClaim:
              claimName: NAME-content-volume
          - name: hashfile-volume
            persistentVolumeClaim:
              claimName: NAME-hashfile-volume
          restartPolicy: OnFailure
          