apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: postgres
spec:
  storageClassName: REPLACEME
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: REPLACEME