apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: c4k-common-cert
  labels:
    app.kubernetes.part-of: c4k-common-app
  namespace: default
spec:
  secretName: c4k-common-cert
  commonName: FQDN
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  dnsNames:
  - FQDN
  issuerRef:
    name: staging
    kind: ClusterIssuer
    