kind: Service
apiVersion: v1
metadata:
  name: taiga-async
  labels:
    app.kubernetes.part-of: c4k-taiga
    app.kubernetes.io/component: taiga-async
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: taiga-async
  ports:
    - name: http
      targetPort: http
      port: 8000
      protocol: TCP            
      