apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-async-deployment
  namespace: taiga
  labels:
    app.kubernetes.part-of: c4k-taiga
    app.kubernetes.io/component: taiga-async
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: taiga-async
  template:
    metadata:
      labels:
        app.kubernetes.io/component: taiga-async
    spec:
      containers:
      - name: taiga-async
        image: taigaio/taiga-back:latest 
        imagePullPolicy: IfNotPresent
        command: ["/taiga-back/docker/async_entrypoint.sh"]
        ports:
        - name: http
          containerPort: 8000
        volumeMounts:
        - name: taiga-static
          mountPath: /taiga-back/static
          readOnly: false
        - name: taiga-media
          mountPath: /taiga-back/media
          readOnly: false
        envFrom:
        - configMapRef:
            name: taiga-configmap
        - secretRef:
            name: taiga-secret
        env:
          - name: POSTGRES_USER 
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres-db
          - name: POSTGRES_HOST
            value: "postgresql-service"
          - name: POSTGRES_PORT
            value: "5432"
      volumes:
        - name: taiga-static
          persistentVolumeClaim:
            claimName: taiga-static-data
        - name: taiga-media
          persistentVolumeClaim:
            claimName: taiga-media-data
