kind: Service
apiVersion: v1
metadata:
  name: taiga-events-rabbitmq
  labels:
    app.kubernetes.part-of: c4k-taiga
    app.kubernetes.io/component: taiga-events-rabbitmq
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: taiga
  ports:
    - name: amqp
      targetPort: amqp
      port: 5672
      protocol: TCP            
      