kind: Service
apiVersion: v1
metadata:
  name: taiga-protected
  labels:
    app.kubernetes.part-of: c4k-taiga
    app.kubernetes.io/component: taiga-protected
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: taiga
  ports:
    - name: http
      targetPort: http
      port: 8003
      protocol: TCP            
      