apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taiga-events-rabbitmq-data
  namespace: taiga
  labels:
    app.kubernetes.part-of: c4k-taiga
spec:
  storageClassName: REPLACEME
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: REPLACEME
