apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-events-deployment
  labels:
    app.kubernetes.part-of: c4k-taiga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiga
  template: 
    metadata:
      labels:
        app: taiga
    spec:
      containers:
      - name: taiga-events
        image: taigaio/taiga-events:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8888
        envFrom: # ToDo: check if all vars are needed
        - configMapRef:
          name: taiga-configmap
        env:
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: taiga-secret
              key: RABBITMQ_USER
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: taiga-secret
              key: RABBITMQ_PASS
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: taiga-secret
              key: TAIGA_SECRET_KEY

