apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-protected-deployment
  labels:
    app.kubernetes.part-of: c4k-taiga
    app.kubernetes.io/component: taiga-protected
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiga
  template: 
    metadata:
      labels:
        app: taiga
    spec:
      containers:
      - name: taiga-protected
        image: taigaio/taiga-protected:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8003
        env:
        - name: MAX_AGE
          value: "5"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: taiga-secret
              key: TAIGA_SECRET_KEY
