apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-front-deployment
  labels:
    app.kubernetes.part-of: c4k-taiga
    app.kubernetes.io/component: taiga-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiga
  template: 
    metadata:
      labels:
        app: taiga
    spec:
      containers:
      - name: taiga-front
        image: taigaio/taiga-front:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        env:
        - name: TAIGA_URL
          value: TAGA_SCHEME://TAIGA_DOMAIN
        - name: TAIGA_WEBSOCKETS_URL
          value: WEBSOCKETS_SCHEME://TAIGA_DOMAIN
        - name: TAIGA_SUBPATH
          value: SUBPATH
