apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taiga-async-rabbitmq-data
  namespace: default
  labels:
    app: taiga
    app.kubernetes.part-of: taiga
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taiga-events-rabbitmq-data
  namespace: default
  labels:
    app: taiga
    app.kubernetes.part-of: taiga
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
