apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-events-deployment
  labels:
    app.kubernetes.part-of: c4k-taiga
    app.kubernetes.io/component: taiga-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiga # ToDo: Check for consistent labels (maybe use app.kubernetes.io)
  template: 
    metadata:
      labels:
        app: taiga
    spec:
      containers:
      - name: taiga-events
        image: taigaio/taiga-events:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8888
        env:
        - name: EVENTS_PUSH_BACKEND_URL # ToDo: check if we really need to set these URLs
          valueFrom:
            configMapKeyRef:
              name: taiga-configmap
              key: EVENTS_PUSH_BACKEND_URL
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: taiga-secret
              key: RABBITMQ_USER
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: taiga-secret
              key: RABBITMQ_PASS
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: taiga-secret
              key: TAIGA_SECRET_KEY

