apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-protected-deployment
  labels:
    app.kubernetes.part-of: c4k-taiga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taiga
  template: 
    metadata:
      labels:
        app: taiga
    spec:
      - name: taiga-protected
        image: taigaio/taiga-protected:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom: # ToDo secret key ref - secret_key
        - secretRef:
          name: taiga-back-secret
        env:
        - name: MAX_AGE
          value: ATTACHMENTS_MAX_AGE
