apiVersion: v1
kind: ConfigMap
metadata:
  name: taiga-configmap
  namespace: default
data:
  # These environment variables will be used by taiga-back and taiga-async.
  # Database settings handled in deployment

  # Taiga settings
  TAIGA_SITES_SCHEME: TAIGA_SCHEME
  TAIGA_SITES_DOMAIN: TAIGA_DOMAIN
  TAIGA_SUBPATH: SUBPATH

  # Email settings.
  EMAIL_BACKEND: EMAIL_BACKEND # django.core.mail.backends.${EMAIL_BACKEND}.EmailBackend # ToDo move to code base
  DEFAULT_FROM_EMAIL: DEFAULT_FROM_EMAIL_VALUE
  EMAIL_USE_TLS: EMAIL_USE_TLS_VALUE
  EMAIL_USE_SSL: EMAIL_USE_SSL_VALUE
  EMAIL_HOST: EMAIL_HOST_VALUE
  EMAIL_PORT: EMAIL_PORT_VALUE

  # Telemetry settings
  ENABLE_TELEMETRY: ENABLE_TELEMETRY_VALUE
  # ...your customizations go here

  # Taiga Events Settings
  EVENTS_PUSH_BACKEND_URL: RABBITMQ_URL_VALUE
  ## Format RABBITMQ_URL="amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@taiga-events-rabbitmq:5672/taiga"
  RABBITMQ_URL: RABBITMQ_URL_VALUE # found in https://github.com/kaleidos-ventures/taiga-events/blob/main/docker/env.template

  # Taiga Async Settings
  CELERY_BROKER_URL: CELERY_URL_VALUE